# Generated by Django 3.0.5 on 2020-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200520161131808738', max_length=50, primary_key=True, serialize=False),
        ),
    ]
