# Generated by Django 3.0.5 on 2020-06-09 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_auto_20200609_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 9, 9, 40, 20, 895455), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200609094020889642', max_length=50, primary_key=True, serialize=False),
        ),
    ]
