# Generated by Django 3.0.5 on 2020-05-22 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_auto_20200520_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Date_Entree',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name="Date d'entrée *"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200522164816674275', max_length=50, primary_key=True, serialize=False),
        ),
    ]
