# Generated by Django 3.0.5 on 2020-06-17 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_auto_20200609_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission',
            name='Date_Permission',
            field=models.DateField(default=datetime.date(2020, 6, 17)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 17, 11, 4, 28, 511749), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200617110428509100', max_length=50, primary_key=True, serialize=False),
        ),
    ]
