# Generated by Django 3.0.5 on 2020-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_auto_20200522_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Date_Sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200522164851942786', max_length=50, primary_key=True, serialize=False),
        ),
    ]
