# Generated by Django 3.0.5 on 2020-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20200522_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='CIN',
            field=models.CharField(blank=True, help_text="Numéro de votre Carte d'Identité Nationale", max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200522165338695667', max_length=50, primary_key=True, serialize=False),
        ),
    ]
