# Generated by Django 3.0.5 on 2020-06-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_auto_20200617_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='Date_Permission',
            field=models.DateField(default=datetime.date(2020, 6, 18)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 18, 10, 16, 18, 23885), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='presence',
            name='debutPause',
            field=models.DateTimeField(null=True, verbose_name='Heure de début de la Pause'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='finPause',
            field=models.DateTimeField(null=True, verbose_name='Heure de fin de la Pause'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heureDepart',
            field=models.DateTimeField(null=True, verbose_name='Heure de Départ'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='status',
            field=models.CharField(choices=[('avance', 'En avance'), ('retard', 'En retard')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200618101618019390', max_length=50, primary_key=True, serialize=False),
        ),
    ]
