# Generated by Django 3.0.5 on 2020-06-22 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_auto_20200618_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='Date_Permission',
            field=models.DateField(default=datetime.date(2020, 6, 22)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 22, 8, 58, 30, 832532), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200622085830829872', max_length=50, primary_key=True, serialize=False),
        ),
    ]
