# Generated by Django 3.0.5 on 2020-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_auto_20200522_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200522170709295272', max_length=50, primary_key=True, serialize=False),
        ),
    ]
