# Generated by Django 3.0.5 on 2020-06-22 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_auto_20200622_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 22, 8, 58, 44, 924898), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200622085844922267', max_length=50, primary_key=True, serialize=False),
        ),
    ]
