# Generated by Django 3.0.5 on 2020-06-24 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_auto_20200622_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='status',
        ),
        migrations.AlterField(
            model_name='permission',
            name='Date_Permission',
            field=models.DateField(default=datetime.date(2020, 6, 24)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 10, 18, 25, 903835), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200624101825901001', max_length=50, primary_key=True, serialize=False),
        ),
    ]
