# Generated by Django 3.0.5 on 2020-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_auto_20200522_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200522171004682585', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Photo',
            field=models.ImageField(upload_to='Fichiers/photos', verbose_name='Photo *'),
        ),
    ]
