# Generated by Django 3.0.5 on 2020-06-24 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_auto_20200624_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='Status',
            field=models.CharField(choices=[('Accordée', 'Accordée'), ('En attente', 'En attente'), ('Refusée', 'Refusée')], default='Accordée', max_length=10),
        ),
        migrations.AlterField(
            model_name='presence',
            name='aujourdhui',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 17, 23, 30, 481297), verbose_name="Aujourd'hui"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200624172330477931', max_length=50, primary_key=True, serialize=False),
        ),
    ]
