# Generated by Django 3.0.5 on 2020-07-07 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_auto_20200707_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='aujourdhui',
        ),
        migrations.AddField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 7), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='debutPause',
            field=models.TimeField(null=True, verbose_name='Heure de début de la Pause'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='finPause',
            field=models.TimeField(null=True, verbose_name='Heure de fin de la Pause'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heureArrivee',
            field=models.TimeField(verbose_name="Heure d'Arrivée"),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heureDepart',
            field=models.TimeField(null=True, verbose_name='Heure de Départ'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default='20200707104146907122', max_length=50, primary_key=True, serialize=False),
        ),
    ]
